name: Run Python Templates

on:
  schedule:
    # Run every weekday at 9:00 AM UTC
    - cron: '0 9 * * 1-5'

jobs:
  run-climatic-chamber-scripts:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install tofupilot package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tofupilot

      # Set TOFUPILOT_API_KEY and run all Python files in corresponding folder
      - name: Run Climatic Chamber scripts
        env:
          TOFUPILOT_API_KEY: ${{ secrets.CLIMATIC_CHAMBER_API_KEY }}
        run: |
          for file in src/climatic_chamber/python-client/*.py; do
            python "$file"
          done
